package com.mycompany.loantracker;

import javax.swing.JOptionPane;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JJP
 */
public class AddALoan extends javax.swing.JFrame {
    
    private TrackAPayment trackAPayment; // Instance of TrackAPayment to set values

    /**
     * Creates new form AddALoan
     */
    public AddALoan() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jbtnSubmit = new javax.swing.JButton();
        jbtnBackToAddTrack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car Loan", "House Loan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(600, 330, 460, 60);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Type of Loan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 290, 140, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Add a Loan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(79, 50, 290, 64);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Name of Borrower");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 170, 196, 32);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 210, 458, 62);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Amount Requested");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 290, 206, 32);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 330, 458, 62);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Due");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 170, 44, 32);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(600, 210, 458, 62);

        jbtnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnSubmit.setText("Submit");
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSubmit);
        jbtnSubmit.setBounds(600, 410, 120, 39);

        jbtnBackToAddTrack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnBackToAddTrack.setText("Back");
        jbtnBackToAddTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackToAddTrackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBackToAddTrack);
        jbtnBackToAddTrack.setBounds(430, 410, 104, 39);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carl Joshua\\Downloads\\loantracker\\loantracker\\src\\main\\java\\com\\mycompany\\loantracker\\Blue and White Modern Company Meeting Zoom Virtual Background.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -30, 1280, 720);

        pack();
    }// </editor-fold>                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jbtnBackToAddTrackActionPerformed(java.awt.event.ActionEvent evt) {                                                   

        AddTrack at = new AddTrack();
        at.setExtendedState(JFrame.MAXIMIZED_BOTH); // Set to full-screen mode
        at.setVisible(true);
        at.show();
        dispose();
    }                                                  

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                           
    // Get values from text fields
        String borrowerName = jTextField2.getText();
        double amountRequested = Double.parseDouble(jTextField1.getText());
        String dueDate = jTextField3.getText();

        // Create an instance of TrackAPayment and update the table with loan data
        TrackAPayment trackAPayment = new TrackAPayment();
        trackAPayment.updateTable(borrowerName, amountRequested, dueDate);

        // Show TrackAPayment frame
        trackAPayment.setVisible(true);
        dispose();

        JOptionPane.showMessageDialog(this, "Submitted!");
        
    }                                          

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddALoan addALoan = new AddALoan();
                addALoan.setExtendedState(JFrame.MAXIMIZED_BOTH);
                addALoan.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtnBackToAddTrack;
    private javax.swing.JButton jbtnSubmit;
    // End of variables declaration                   
}