package com.mycompany.loantracker;

import javax.swing.JOptionPane;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JJP
 */
public class AddTrack extends javax.swing.JFrame {

    /**
     * Creates new form AddTrack
     */
    public AddTrack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnAddLoan = new javax.swing.JButton();
        jbtnTrackPayment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton2.setText("Add a loan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton3.setText("Add a loan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Loan Tracker");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 40, 300, 64);

        jbtnAddLoan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnAddLoan.setText("Add a loan");
        jbtnAddLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddLoanActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAddLoan);
        jbtnAddLoan.setBounds(300, 330, 230, 55);

        jbtnTrackPayment.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnTrackPayment.setText("Track a Payment");
        jbtnTrackPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTrackPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTrackPayment);
        jbtnTrackPayment.setBounds(640, 330, 290, 55);

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 10, 110, 50);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddLoanActionPerformed
        // TODO add your handling code here:
         AddALoan al = new  AddALoan();
        al.setExtendedState(JFrame.MAXIMIZED_BOTH); // Set to full-screen mode
        al.setVisible(true);
        TrackAPayment trackpayment = new TrackAPayment();
        trackpayment.show();
        
        al.show();  
        dispose();
        
    }//GEN-LAST:event_jbtnAddLoanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnTrackPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTrackPaymentActionPerformed
        TrackAPayment tp = new  TrackAPayment();
        tp.setExtendedState(JFrame.MAXIMIZED_BOTH); // Set to full-screen mode
        tp.setVisible(true);
        TrackAPayment trackpayment = new TrackAPayment();
        trackpayment.show();
        
        tp.show();
        dispose();
    }//GEN-LAST:event_jbtnTrackPaymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         UserInfo ui = new UserInfo();
        ui.setExtendedState(JFrame.MAXIMIZED_BOTH); // Set to full-screen mode
        ui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        UserInfo ui = new UserInfo();
        ui.show();
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTrack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddTrack addTrack = new AddTrack();
            addTrack.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximize the window
            addTrack.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAddLoan;
    private javax.swing.JButton jbtnTrackPayment;
    // End of variables declaration//GEN-END:variables
}
